from pathlib import Path
import json,re,hashlib
R=Path(__file__).resolve().parents[3];out=R/'inventory/engine/pilot/oil-cap';ref=R/'reference/engine/pilot/oil-cap'
s=(ref/'ford.html').read_text().replace('\\"','"')
fit=json.loads(re.search(r'\{"text":"Ford_F-150_1994__4.9 Gas_[^}]+\}',s).group())
e={'date':'2026-09-26','scope':'1994 Ford F-150 4.9L oil filler cap; replacement-style candidate, not measured factory reconstruction','sources':[
{'id':'pilot-oil-cap-ford','url':'https://www.ford.com/product/engine-oil-filler-cap-p4000083484','publisher':'Ford Motor Company','part':'EC743 / F3AZ6766B','application':fit,'capture':'reference/engine/pilot/oil-cap/ford.html','facts':['Exact target application is present in embedded product fitment data.','Primary top and underside photos establish scalloped hand grip, closed male screw stem, underside molding relief and annular seal.'],'images':[{'file':'ford-cap.jpg','url':'https://nvc-feil-prod-gcsproxy.ford.com/feil-image-upload-bucket-p/parts/images/photo-images/648/726648.jpg'},{'file':'ford-bottom.jpg','url':'https://nvc-feil-prod-gcsproxy.ford.com/feil-image-upload-bucket-p/parts/images/photo-images/647/726647.jpg'}]},
{'id':'pilot-oil-cap-motorad','url':'https://motorad.com/part/MO100/','publisher':'MotoRad','capture_method':'Web retrieval; direct HTTP returned denial; rejected HTTP response retained separately','facts':['MO100 cross-references Ford F3AZ6766B and Motorcraft EC743.','Nonvented black plastic cap with included preinstalled rubber seal and male screw retention.'],'dimensions_mm':{'neck_diameter':31.24,'shell_outside_diameter':69.09,'overall_height':38.10},'dimension_scope':'Published replacement comparison only; no proof these are Ford EC743 dimensions.'},
{'id':'pilot-oil-cap-dorman','url':'https://www.dormanproducts.com/p-84374-90005.aspx','publisher':'Dorman','capture':'reference/engine/pilot/oil-cap/dorman.html','facts':['90005 crosses EC743 and F3AZ6766B; nylon screw-on cap.'],'catalog_dimensions_in':{'diameter':2.75,'height':0.5},'conflict':'Height differs from MotoRad 1.5 in. Measurement scope is unclear. Not averaged or silently promoted to Ford dimensions.'}],
'geometry_assumptions':['Four scallops reconstructed from Ford photo; shape, depth and wall thickness estimated.','Thread pitch 4.5 mm, triangular profile and 18 mm engaged length are illustrative; no sourced tolerance or lead.','Seal OD44 ID31.6 thickness3 mm chosen for the frozen cover datum; rubber compound and compression unknown.','Overall envelope uses MotoRad replacement comparison dimensions, not verified Ford dimensions.'],
'acceptance_blockers':['Frozen cover lacks female threads and has diameter34 opening; candidate male thread is31.24 mm. No retention contact.','Source photo supports construction but not exact production dimensions or installed part identity.','Seal contact is geometric only; no compression, pressure, heat or material validation.']}
e['capture_sha256']={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in ref.iterdir() if p.suffix in ['.html','.jpg']}
(out/'evidence.json').write_text(json.dumps(e,indent=2)+'\n')
(ref/'motorad-web-extract.json').write_text(json.dumps(e['sources'][1],indent=2)+'\n')
learning={'oil-filler-cap':{'summary':'The oil cap closes the valve-cover fill opening. Male screw retention holds a nonvented closure against an annular rubber seal. Ford lists EC743/F3AZ6766B for the 1994 F-150 4.9 Gas application.','limits':'Candidate only: the cover opening is smooth, so screw engagement fails. Published MotoRad dimensions are replacement comparisons; Ford contours, thread lead, seal dimensions and tolerances require measurement.','steps':[{'title':'Follow the load path','text':'Hand force on the scalloped rim turns the screw stem. In a complete neck, female threads provide axial clamp force for the sealing ring. The current frozen cover does not contain that interface.','source':'pilot-oil-cap-ford'},{'title':'Separate retention from sealing','text':'The thread locates and retains the cap; the rubber annulus closes the oil-fill joint. A modeled touch between flat faces does not establish leak-tight compression.','part':'oil-filler-cap-seal'},{'title':'Keep the ventilation path distinct','text':'MotoRad identifies this replacement cap as nonvented. It is not the PCV valve or crankcase breather. No operating motion or airflow through the cap is modeled.','source':'pilot-oil-cap-motorad'},{'title':'Inspect the actual joint','text':'Oil around the cap may justify inspecting the ring for damage, dirt or flattening and the cap and neck for cracked or damaged retention. This model cannot diagnose an actual leak or establish tightening torque.','source':'pilot-oil-cap-motorad'}],'sources':['pilot-oil-cap-ford','pilot-oil-cap-motorad','pilot-oil-cap-dorman']},'oil-filler-cap-seal':{'summary':'A separate rubber annulus seals between the oil filler cap and neck.','limits':'OD44, ID31.6 and thickness3 mm are assumptions matched to the provisional cover. Compression and rubber grade are unknown.','steps':[{'title':'Two contact faces','text':'The lower face touches the frozen cover at world Z413; the upper face touches the cap boss at Z416. The ring remains a separate part for inspection and learning.','part':'oil-filler-cap'}],'sources':['pilot-oil-cap-ford','pilot-oil-cap-motorad']}}
(out/'learning.json').write_text(json.dumps(learning,indent=2)+'\n')
print('Evidence and learning written; exact application extracted from Ford capture.')
