#!/usr/bin/env python3
"""Index local engine evidence; catalog entries are NOT a complete physical BOM."""
from pathlib import Path
from urllib.parse import quote, unquote
import hashlib
import json
import re
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
MANUAL = ROOT / 'manuals/factory-service-manual/1994 Ford F 150 2WD Pickup L6-300 4.9L'
SECTION = 'Engine%2C%20Cooling%20and%20Exhaust/Engine'
BASE = 'https://charm.li/Ford/1994/F%20150%202WD%20Pickup%20L6-300%204.9L/'


def slug(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')


def main():
    pages, catalog = [], []
    for branch in ['Repair%20and%20Diagnosis', 'Parts%20and%20Labor']:
        folder = MANUAL / branch / SECTION
        if not folder.is_dir():
            raise SystemExit('Restore the manual with scripts/fetch-manuals.sh first')
        for path in sorted(folder.rglob('index.html')):
            raw = path.read_bytes()
            soup = BeautifulSoup(raw, 'html.parser')
            content = soup.select_one('.main')
            if content is None:
                raise ValueError(f'Missing manual content: {path}')
            rel = path.relative_to(MANUAL)
            labels = [unquote(x) for x in rel.parts[:-1]]
            sid = 'fsm-' + hashlib.sha256(str(rel).encode()).hexdigest()[:12]
            text = content.get_text('\n', strip=True)
            images = []
            for im in content.find_all('img'):
                ip = (path.parent / unquote(im['src'])).resolve()
                if not ip.is_relative_to(MANUAL) or not ip.is_file():
                    raise ValueError(f'Missing or unsafe image: {ip}')
                images.append({'path': str(ip.relative_to(ROOT)),
                               'sha256': hashlib.sha256(ip.read_bytes()).hexdigest()})
            record = {'id': sid, 'title': ' / '.join(labels[2:]),
                      'path': str(path.relative_to(ROOT)),
                      'url': BASE + '/'.join(quote(unquote(x), safe='') for x in rel.parts[:-1]) + '/',
                      'sha256': hashlib.sha256(raw).hexdigest(),
                      'main_text_sha256': hashlib.sha256(text.encode()).hexdigest(),
                      'images': images, 'text': text,
                      'review_status': 'indexed-not-validated'}
            pages.append(record)
            if branch == 'Parts%20and%20Labor' and labels[-1] == 'Parts Information':
                tables = [[[cell.get_text(' ', strip=True) for cell in tr.find_all(['td', 'th'])]
                           for tr in table.find_all('tr')] for table in content.find_all('table')]
                name = labels[-2]
                catalog.append({'id': slug(name), 'name': name, 'source_id': sid,
                                'tables': tables, 'quantity_installed': None,
                                'entry_kind': 'service-kit' if 'Kit' in name else 'catalog-category',
                                'physical_decomposition_status': 'pending',
                                'note': 'A catalog category or service package is not necessarily one physical part.'})
    ids = [p['id'] for p in pages]
    assert len(ids) == len(set(ids))
    data = {'schema_version': 1, 'vehicle': '1994 F-150 2WD 4.9L I6',
            'scope': 'Engine subtree only; not all attached systems or a complete fastener BOM.',
            'sources': pages, 'catalog_entries': catalog}
    out = ROOT / 'inventory/engine'
    out.mkdir(parents=True, exist_ok=True)
    (out / 'research-index.json').write_text(json.dumps(data, indent=2) + '\n')
    image_count = len({x['sha256'] for p in pages for x in p['images']})
    report = ['---', 'title: "Engine research coverage and unresolved geometry"', '---', '',
              'Generated by `python3 scripts/audit_engine.py` from the restored manual.', '',
              f'- {len(pages)} engine-subtree pages indexed with content hashes.',
              f'- {image_count} unique diagram/image contents linked to their source pages.',
              f'- {len(catalog)} parts-information categories extracted with their original tables.',
              '- Quantities remain unknown until a diagram or other source establishes them.',
              '- These counts measure indexed material, not verified parts or modeling completeness.', '',
              '## Sources and gaps', '',
              'See `inventory/engine/dimensions.json` for reviewed claims, application limits and',
              'blocked values. See `inventory/engine/first-assembly.json` for modeled occurrences.',
              'The manufacturer PDFs are local research assets in `reference/engine/`.', '',
              'Priority gaps: rod center distance; actual piston identity and pin offset; piston',
              'skirt and pin-boss dimensions; big-end width and housing bore; fastener dimensions;',
              'crank web geometry and cylinder spacing; exact casting passages; complete hardware counts.', '',
              'The first CAD assembly is an explicitly provisional geometric reconstruction.',
              'It combines factory dimensions, replacement-part catalog dimensions and listed',
              'modeling assumptions. It is not a certified OEM replica or a machining drawing.', '',
              '## Catalog categories', '', '| Category | Classification | Reference |',
              '|---|---|---|']
    by_id = {p['id']: p for p in pages}
    for c in catalog:
        report.append(f"| {c['name']} | {c['entry_kind']} | [Manual]({by_id[c['source_id']]['url']}) |")
    dimensions_path = out / 'dimensions.json'
    if dimensions_path.exists():
        dimensions = json.loads(dimensions_path.read_text())
        report += ['', '## Reviewed dimensions and modeling assumptions', '',
                   'Values below are in millimeters. A replacement-reference dimension belongs',
                   'to the cited replacement design; it is not certified as original equipment.', '',
                   '| Parameter | Value | Evidence status | Application / gap |', '|---|---|---|---|']
        for c in dimensions['claims']:
            report.append(f"| {c['id']} | {c['value']} | {c['status']} | {c['note']} |")
        report += ['', '## Blocked claims', '']
        for c in dimensions['blocked_claims']:
            report.append(f"- **{c['id']}**: {c['reason']}")
    (ROOT / 'docs/ENGINE-AUDIT.md').write_text('\n'.join(report) + '\n')
    print(json.dumps({'pages': len(pages), 'unique_images': image_count, 'catalog_categories': len(catalog)}))


if __name__ == '__main__':
    main()
