"""Freeze an explicitly identified accepted baseline and build all12 candidate.

Does not write installed manifest, STEP or GLB. Caller supplies accepted hash.
"""
from pathlib import Path
from copy import deepcopy
import argparse,json,hashlib,shutil,sys
import build123d as b
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'cad/engine'))
import valve_source_layout as v
from valve_source_integration import annotate_manifest,replacements
p=argparse.ArgumentParser();p.add_argument('--baseline',required=True,type=Path);p.add_argument('--expected-manifest',required=True);a=p.parse_args()
OUT=ROOT/'cad/engine/candidates/valve-source-all12';BASE=OUT/'baseline';BASE.mkdir(parents=True,exist_ok=True)
mp=a.baseline/'inventory/engine/full-assembly.json';raw=mp.read_bytes();digest=hashlib.sha256(raw).hexdigest()
assert digest==a.expected_manifest,('Source manifest changed',digest)
if (BASE/'manifest.json').exists():assert (BASE/'manifest.json').read_bytes()==raw,'Refuse to replace candidate baseline'
else:(BASE/'manifest.json').write_bytes(raw)
m=json.loads(raw);dmap={d['id']:d for d in m['definitions']};hashes={};STEP=BASE/'generated';STEP.mkdir(exist_ok=True)
for d in m['definitions']:
 path=a.baseline/d['step'].lstrip('/');target=STEP/(d['id']+'.step');h=hashlib.sha256(path.read_bytes()).hexdigest();hashes[d['id']]=h
 if target.exists():assert hashlib.sha256(target.read_bytes()).hexdigest()==h,('Frozen source differs',d['id'])
 else:shutil.copy2(path,target)
for name in ['assembly_math.py']:
 path=a.baseline/'cad/engine'/name;target=BASE/name
 if not target.exists():shutil.copy2(path,target)
 else:assert target.read_bytes()==path.read_bytes()
assert hashlib.sha256(mp.read_bytes()).hexdigest()==digest,'Baseline manifest changed during snapshot'
needed=['cylinder-head','lifter-body','intake-valve','exhaust-valve']
current={n:b.import_step(STEP/(n+'.step')) for n in needed}
shapes=replacements(current,m);candidate=annotate_manifest(m);definitions={d['id']:d for d in candidate['definitions']}
for kind in v.LENGTHS:
 name=kind+'-spring'
 if name not in definitions:
  row=deepcopy(definitions['valve-spring']);row.update(id=name,name=kind.title()+' valve spring');candidate['definitions'].append(row);definitions[name]=row
for name,s in shapes.items():
 assert s.is_valid and len(s.solids())==1,(name,len(s.solids()))
 b.export_step(s,OUT/(name+'.step'));box=s.bounding_box();row=definitions[name]
 row.update(step='/'+str((OUT/(name+'.step')).relative_to(ROOT)),volume_mm3=s.volume,solid_count=1,model_bounds_mm=list(box.size))
 row['unresolved']=list(row.get('unresolved',[]))+['Source-sized candidate: replacement envelope constraints are not installed part identification; absolute casting and lifter-seat/rocker geometry remain assumed.']
for name,row in definitions.items():
 if name not in shapes:row['step']='/'+str((STEP/(name+'.step')).relative_to(ROOT))
# GLB routes are deliberately not regenerated by this CAD-only candidate builder.
candidate['candidate_scope']='Source-sized all12 CAD candidate; requires independent static/motion/GLB integration QC.'
(OUT/'manifest.json').write_text(json.dumps(candidate,indent=2)+'\n')
report=v.metadata();report.update(baseline_root=str(a.baseline),baseline_manifest_sha256=digest,baseline_step_hashes=hashes,shape_hashes={n:hashlib.sha256((OUT/(n+'.step')).read_bytes()).hexdigest() for n in shapes},baseline_transform_sha256=hashlib.sha256((BASE/'assembly_math.py').read_bytes()).hexdigest())
(OUT/'provenance.json').write_text(json.dumps(report,indent=2)+'\n');print('Built all12 source-sized candidate',len(shapes),'definitions',len(candidate['occurrences']),'occurrences')
