"""Bind frozen study evidence; preserve original broad guard FAIL."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[1];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
names=['timing-seven-block-guard-study','timing-seven-block-functional-guards','timing-seven-block-neighbors','timing-seven-block-mesh-review','timing-seven-block-visual-review','timing-seven-block-guard-localization','timing-seven-block-failure-location-visual','timing-seven-block-added-location-visual'];reports={n:json.loads((ROOT/'inventory/engine'/f'{n}.json').read_text())for n in names};mismatches=[]
for name,r in reports.items():
 for p,h in r.get('input_sha256',r.get('inputs_sha256',{})).items():
  if sha(ROOT/p)!=h:mismatches.append({'report':name,'path':p})
a,f,n,m,v=[reports[k]for k in names[:5]];gates={'inputs_current':not mismatches,'declared_stock_cavity_locality':a['gates']['material_locality'],'seven_source_female_wall_floor':a['gates']['source_female_blind_wall_floor'],'original_broad_stock_guards':a['gates']['all_declared_guards_unchanged'],'functional_pan_pump_guards':f['status']=='PASS functional interfaces only','actual_neighbors':n['gates']['actual_neighbors_clear'],'all_angle_new_support_bounds':n['gates']['changed_stock_all_angle'],'metrics_verified':a['gates']['material_metrics_verified']and n['gates']['metrics_verified'],'valid_mesh':m['valid']and m['solids']==1 and m['mesh_watertight']and m['mesh_winding_consistent']and m['mesh_components']==1 and m['mesh_signed_volume_mm3']>0 and m['cad_mesh_bounds_error_mm']<.15};r={'status':'PASS'if all(gates.values())else'FAIL original broad stock guard; assess separately bound functional evidence','gates':gates,'input_mismatches':mismatches,'broad_guard_failures':[x for x in a['guards']if not x['unchanged']],'reports_sha256':{f'inventory/engine/{name}.json':sha(ROOT/'inventory/engine'/f'{name}.json')for name in names},'checker_sha256':sha(Path(__file__)),'limits':['Root must explicitly assess changes in exterior pan20R12 andpumpR85 stock; original strictguardFAIL remains','Measured CAD volumes do not resolve inheritedV3 metric gaps','Only local changed-support motion envelopes qualified; no wholeassembly continuous collision/flow/strength/factory claim','No canonical installation/browser']};(ROOT/'inventory/engine/timing-seven-block-delivery-validation.json').write_text(json.dumps(r,indent=2)+'\n');print(r['status']);print(gates)
