"""Bind scoped reports and delivered units; no geometry regeneration."""
from pathlib import Path
import json,hashlib
import numpy as np,trimesh
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'cad/engine/generated/timing-pan21-lateral-candidate';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
names=['timing-pan21-lateral-candidate-validation','timing-pan21-lateral-interfaces','timing-pan21-actual-gasket-contact','timing-pan21-lateral-neighbors','timing-pan21-main-joint','timing-pan21-lateral-visual-review'];reports={n:json.loads((ROOT/'inventory/engine'/f'{n}.json').read_text())for n in names};mismatch=[]
for n,r in reports.items():
 for path,h in r.get('inputs_sha256',{}).items():
  if sha(ROOT/path)!=h:mismatch.append({'report':n,'path':path})
b=reports[names[0]];i=reports[names[1]];a=reports[names[2]];n=reports[names[3]];j=reports[names[4]];units={}
for name in ['cover','pan','pan-gasket']:
 mesh=trimesh.load(OUT/(name+'.glb'),force='mesh');v=mesh.vertices[:,[0,2,1]]*[1,-1,1]*1000;native=np.load(OUT/(name+'-preview.npz'))['vertices'];units[name]={'glb_bounds_error_mm':float(np.max(np.abs(np.array([v.min(0),v.max(0)])-np.array([native.min(0),native.max(0)])))),'watertight':mesh.is_watertight,'positive_volume':bool(mesh.volume>0),'winding_consistent':mesh.is_winding_consistent}
gates={'report_inputs_current':not mismatch,'initial_interfaces':b['initial_status']=='PASS','all25_seats_and_clearance':all(v<1e-5 for r in i['hardware25']for k,v in r.items()if k not in ['station','position_mm']),'material_locality':all(v<1e-5 for r in i['locality'].values()for v in r.values()),'actual_changed_gasket_contact':a['status']=='PASS','seven_main_joints':j['status']=='PASS','actual_neighbors':all(r['new_cover_overlap_mm3']==0 and r['new_stock_overlap_mm3']==0 for r in n['neighbors']),'newstock_allangle_bounds':all(r.get('separation_lower_mm',1)>0 for r in n['new_stock_continuous_rotation_bounds']),'dry_wall_negative_control':i['wet_dry_witnesses']['dry_to_wet_wall_obstruction']>.1 and i['wet_dry_witnesses']['breached_wall_negative_control_obstruction']<1e-5,'wet_witnesses':all(r['cover_obstruction']+r['pan_obstruction']<1e-5 and r['blocked_negative_control']>.1 for r in i['wet_dry_witnesses']['cavity_bypass']),'mesh_and_units':all(r['watertight']and r['positive_volume']and r['winding_consistent']and r['glb_bounds_error_mm']<.01 for r in units.values()),'bom25_and_gasket_topology':i['bom']['pan_screws']==25 and i['bom']['unique_axes']==25 and i['meshes']['pan-gasket']['euler_number']==-50,'no_measurement_errors':not any(r.get('errors',r.get('measurement_errors',{}))for r in reports.values())}
r={'status':'PASS scoped pan21 relocation; not installed'if all(gates.values())else'FAIL scoped delivery','gates':gates,'input_mismatches':mismatch,'units':units,'reports_sha256':{f'inventory/engine/{name}.json':sha(ROOT/'inventory/engine'/f'{name}.json')for name in names},'artifacts_sha256':{str(p.relative_to(ROOT)):sha(p)for p in OUT.iterdir()if p.suffix in ['.step','.glb','.png','.npz','.json']},'checker_sha256':sha(Path(__file__)),'limits':['Estimated blind boss occupies local inferred cover cavity; no unchanged-cavity/factory/strength claim','Initial overbroadR10 contact witness retained; actualgasket support is separately bound','Frozen v2 pan rear contact gaps remain; subsequent root contact patches not composed','Seven-screw comparison block broader guards remain unverified; this check certifies pan21 delta only','Finite wet paths and local all-angle radial bounds do not prove full containment/motion','Browser and installation NOT RUN']};(ROOT/'inventory/engine/timing-pan21-lateral-delivery-validation.json').write_text(json.dumps(r,indent=2)+'\n');print(r['status']);print(gates)
