from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();names=['timing-pump-rear-flange-export','timing-pump-rear-flange-validation','timing-pump-rear-flange-access-evidence','timing-pump-rear-flange-visual-review','timing-pump-rear-flange-strip-topology'];reports={n:json.loads((R/'inventory/engine'/f'{n}.json').read_text())for n in names};mismatches=[]
for name,j in reports.items():
 for p,h in j['inputs'].items():
  if sha(R/p)!=h:mismatches.append([name,p])
e=reports[names[0]];v=reports[names[1]];a=reports[names[2]]
gates={'inputs_current':not mismatches,'valid_exports':all(q['valid']and q['watertight']and q['components']==1 and q['mesh_bounds_error_mm']<.025 for q in e['parts'].values()),'rear_part_fit':v['gates']['rear_no_overlap'],'full_gasket_face_contact':v['gates']['complete_gasket_faces'],'connected_3mm_stock':v['gates']['connected_3mm_strip'],'closed_3mm_separation_topology':all(q['candidate']['same_separation_topology'] for q in reports[names[4]]['rows'].values()),'exact_changed_material_locality':v['gates']['locality'],'nominal_pump_head_bearing_support':all(q['required_bearing_missing_mm2']<1e-5 for q in a['pump_bearing_faces']),'all7_main_headseats_and_rear_lands':all(q['headseat_missing_mm3']+q['R9_land_removed_mm3']<1e-5 for q in v['main_hardware']),'declared_main3_rear_tool_access':v['main_hardware'][2]['tool_pump_rear_mm3']<1e-5,'all_pump_nominal_tool_access':all(q['new_tool_housing_overlap_mm3']<1e-5 for q in a['pump_bearing_faces']),'main3_continuous_screw_withdrawal':a['screw_withdrawal'][0]['envelope_pump_overlap_mm3']<1e-5,'source_justifies_pump_absent_access':False,'forward_inlet_fit':v['pairs']['cover__housing']['full_overlap_mm3']<.1}
r={'status':'FAIL access, inherited pump strip topology and forward inlet remain; rearfit/contact/export gates individually pass','gates':gates,'input_mismatches':mismatches,'reports_sha256':{str((R/'inventory/engine'/f'{n}.json').relative_to(R)):sha(R/'inventory/engine'/f'{n}.json')for n in names},'artifacts_sha256':{str(p.relative_to(R)):sha(p)for p in (R/'cad/engine/generated/timing-pump-rear-flange-candidate').iterdir()if p.suffix in ['.step','.glb','.png','.npz']},'checker_sha256':sha(Path(__file__)),'limits':['No canonical/private-stage changes or installation claim.','NominalR9guardmargin0.1556339mm; +0.16mmradius violatesstockguard, +0.5mm begins headseatloss.','Originalrawheadfacegap retained and explained asclearanceannulus; actualbearingfaces supported.','Whole-sourcepump axis, inlet, core andmainholes unchanged; earlier failures retained.']};(R/'inventory/engine/timing-pump-rear-flange-delivery.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r,indent=2))
