from pathlib import Path
import json,hashlib,numpy as np
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'reference/engine';GEN=ROOT/'cad/engine/generated/fuel-rail-candidate-20261003/r4'
s=json.loads((GEN/'pressure-section.json').read_text());fig,ax=plt.subplots(1,2,figsize=(14,7));colors={'regulator-lower-housing':'#377eb8','regulator-upper-housing':'#333333','regulator-diaphragm':'#b83395','fuel-supply-rail':'#999999','fuel-return-tube':'#be771f','regulator-o-ring':'#222222'}
for a in ax:
 for ident,row in s.items():
  for n,line in enumerate(row['polylines_r_z_mm']):
   p=np.array(line);a.plot(p[:,0],p[:,1],color=colors.get(ident,'#999999'),lw=1,label=ident if n==0 else None)
 a.set(xlim=(0,23),ylim=(376,402),xlabel='Radial X offset from regulator axis mm',ylabel='Engine Z mm');a.set_aspect('equal');a.grid(alpha=.2)
ax[0].set_title('Actual r4 STEP section — upper/lower shell gap');ax[0].plot([8,21],[388.5,388.5],color='red',linewidth=3,label='Open exterior path, exact probe');ax[0].legend(fontsize=6,loc='upper left')
for x,z,w,h,color,label in [(17,388,3,1.1,'#228833','A lower wall to diaphragm underside'),(19.8,389.1,.2,.8,'#ccbb44','B outer diaphragm capture band'),(17,389.9,3,.1,'#4477aa','C upper skirt to diaphragm top')]:ax[1].add_patch(Rectangle((x,z),w,h,facecolor=color,label=label))
ax[1].set_title('Proposed estimated shell additions — not yet CAD');ax[1].legend(fontsize=7,loc='upper left')
fig.suptitle('Typical Ford architecture; current metric geometry estimated. O-ring seal and valve mechanics remain open.');fig.tight_layout();fig.savefig(OUT/'fuel-rail-candidate-20261003-pressure-proposal.png',dpi=180)
source=ROOT/'manuals/factory-service-manual/1994 Ford F 150 2WD Pickup L6-300 4.9L/images/DM05Q313/ford10/651252932.png'
r={'status':'NUMERIC PROPOSAL; ROOT REVIEW REQUIRED BEFORE CAD','source':{'path':str(source.relative_to(ROOT)),'sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'caption':'Fuel Pressure Regulator (Typical)','actual_pixels_reviewed':True,'redistribute':False,'claim':'Diaphragm continuously captured at upper/lower housing peripheral joint; spring-side vacuum and pressure-side supply/central-return separated. No numeric internal dimensions.'},'metric_classification':'All inherited or estimated; no pixel-derived millimeter dimensions','external_bounds_preserved':{'outer_housing_radius_mm':20,'diaphragm_radius_mm':19.8,'diaphragm_z_mm':[389.1,389.9],'existing_vacuum_nipple_unchanged':True},'amendments':[{'id':'A','definition':'regulator-lower-housing','radial_interval_mm':[17,20],'world_z_interval_mm':[388,389.1],'local_z_interval_mm':[2,3.1],'purpose':'Extend lower pressure wall to diaphragm underside; lower occurrence originZ386'},{'id':'B','definition':'regulator-lower-housing','radial_interval_mm':[19.8,20],'world_z_interval_mm':[389.1,389.9],'local_z_interval_mm':[3.1,3.9],'purpose':'Continuous peripheral capture band at diaphragm edge, ideal zero-volume cylindrical contact'},{'id':'C','definition':'regulator-upper-housing','radial_interval_mm':[17,20],'world_z_interval_mm':[389.9,390],'local_z_interval_mm':[4.9,5],'purpose':'Bring upper skirt to diaphragm top; upper occurrence originZ385'}],'contact_expectations':{'lower_diaphragm_annulus_mm':[17,19.8],'lower_contact_z_mm':389.1,'upper_diaphragm_annulus_mm':[17,19.8],'upper_contact_z_mm':389.9,'peripheral_contact_radius_mm':19.8,'peripheral_contact_z_mm':[389.1,389.9],'allowed_unintended_solid_interference_mm3':0.1,'physical_compression_or_clamp_force':'Unknown; zero-volume idealized contact only'},'preserve':['Eight feed passages and screen apertures','Supply gallery and isolated central return','Valve-seat r1.8 and seated ball pose','Diaphragm/spring-seat/spring baseline locations','Existing vacuum nipple bore and both transverse signs','All flange screws, inlet socket and gasket interfaces'], 'limits':['Three shell additions do not fix lower uncompressed O-ring clearance or independently establish pressure enclosure.','Valve+0.5mm test is cavity connectivity only; fixed diaphragm is not a validated moving mechanism.','No production crimp thickness, preload, elastomer compression or hydraulic performance specified.'],'checks_required':['Actual STEP annular contact area and no unintended component overlap','Full360degree pressure/vacuum/exterior fluid connectivity with explicitly capped legitimate supply/return/vacuum ports; no hidden artificial sidewall','Keep original open-shell and lower-O-ring-gap negative controls','Valve seated/open local controls and diaphragm barrier with pierced-diaphragm negative','STEP/GLB/context rerun with actual input hashes']}
(OUT/'fuel-rail-candidate-20261003-pressure-proposal.json').write_text(json.dumps(r,indent=2)+'\n');print('proposal and actual-section figure written')
