"""Authored source-point overlay and frozen numerical proposal, no CAD edit."""
from pathlib import Path
import json,hashlib,numpy as np
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle,Circle,FancyBboxPatch
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'reference/engine'
points=[[790,560],[808,558],[831,575],[829,589],[817,612],[805,618],[790,612],[782,600],[786,582],[790,560]]
record={'status':'ROOT REVIEW REQUIRED BEFORE CAD','source':'physical1987_view1; earlier comparison not exact1994','source_sha256':'94bce34481d25306085a0f1fb27481c64f5b07ee5fccb151ed16560469cfddf8','manual_middle_ear_outline_px':points,'manual_pick_uncertainty_px':6,'method':'Manual image-space outline. No metric/projective registration; occluded root uncertain. Authored source polygon shown at left, independent numerical model proposal at right.','proposed_tabs':{'x_centers_mm':[-250,-40,220],'x_half_width_mm':9,'y_interval_mm':[-186,-163],'z_interval_mm':[364,370],'lower_corner_radius_mm':2,'bore_radius_mm':3.4,'hole_y_mm':-178},'protected_regions':{'seat_band_box_xy_mm':[16,12],'seat_center_y_mm':-178,'washer_outer_radius_mm':7,'washer_z_mm':[370,371.5],'bolt_and_hardware':'unchanged'},'evidence_limits':['Only one-sided rounded silhouette is source supported. Numerical width, depth, corner radius and inherited6mm thickness remain model estimates.','Tab outline must preserve exact existing seat geometry, bolt axis and entire washer contact circle in next CAD Boolean verification.','No return path or sign changes. Minus conflicts remain.']}
(OUT/'fuel-rail-candidate-20261003-tab-proposal.json').write_text(json.dumps(record,indent=2)+'\n')
fig,axs=plt.subplots(1,2,figsize=(12,6));p=np.array(points);axs[0].plot(p[:,0],p[:,1],'-o',label='Authored physical middle-ear outline');axs[0].plot(810,590,'rx',label='Existing source hole pick');axs[0].invert_yaxis();axs[0].set_aspect('equal');axs[0].set_title('1987 comparison — image pixels, ±6 px picks');axs[0].legend(fontsize=8)
a=axs[1];a.add_patch(Rectangle((-9,-186),18,46,fill=False,edgecolor='red',linestyle='--',label='Current rectangular tab'));a.add_patch(Rectangle((-9,-186),18,23,fill=False,edgecolor='blue',linewidth=2,label='Proposed one-sided tab envelope'));a.add_patch(Rectangle((-8,-184),16,12,fill=False,edgecolor='green',label='Protected sampled seat'));a.add_patch(Circle((0,-178),7,fill=False,color='orange',label='Existing washer contact'));a.add_patch(Circle((0,-178),3.4,fill=False,color='black'));a.axhspan(-169,-157,color='gray',alpha=.2,label='Supply OD envelope');a.set(xlim=(-22,22),ylim=(-193,-135),xlabel='ΔX mm',ylabel='Engine Y mm',title='Numerical proposal; bottom corners R2 mm');a.set_aspect('equal');a.legend(fontsize=8)
fig.suptitle('Source topology motivates one-sided ears; numerical dimensions remain estimates');fig.tight_layout();fig.savefig(OUT/'fuel-rail-candidate-20261003-tab-proposal.png',dpi=160)
