"""Datum-only proposed API, no geometry generation or manifest writes."""
from pathlib import Path
import json

def pump_height_datums(height_mm=98.43,mount_world_x=375.,axis_yz=(-32.,170.),belt_center_world_x=473.56):
    """Replacement-comparison hypothesis; dimensions are not factory specifications."""
    hub=mount_world_x+height_mm;delta=hub-522.
    return {'frame_origin_world_mm':[mount_world_x,*axis_yz],'axis':'+X toward fan','height_mm':height_mm,'hub_pulley_face_local_x':height_mm,'hub_pulley_face_world_x':hub,'front_stack_translation_mm':delta,'belt_center_world_x':belt_center_world_x,'new_pulley_face_to_belt_center_signed_mm':belt_center_world_x-hub,'shaft_world_x_bounds':[365.,519.+delta],'shaft_length_mm':519.+delta-365.,'protected':['mounting faceX375, gasket/blockfaceX373 and existing four mountaxes','impeller existingX369..384 and rearshaft endpointX365','shaft axisYZ(-32,170)','belt centerX473.56 as existing estimated global anchor, not factory datum'],'rebuild':['housing chamber/taper joining retained rear flange to relocated frontwall/nose; no uniform solid scaling','shaft length keeping rear engagement and matched relocated hub/bearing/seal stations','pulley dish between fixed belt rim and new hub mating face; its old48.44mm dish is not retained','heater/inlet root geometry coordinated with rebuilt chamber; frozen source-route not rigidly adopted'],'translate_front_stack':['drive hub with pilot','bearing cartridge','all six named seal components','slinger','frontwall, bearing bore and weep passage together','pulley mounting web and four bolts only; rim remains at belt datum','fan clutch and fan rigid subgroup, subject to radiator/body clearance NOT RUN'],'gates_open':['replacement-to-GMB dimensional transfer','hub OD/bolt-circle/pilot and fan identity','bearing and mechanical seal internals/pressfits','housing fluidwall and port connections','pulley dish manufacturability/rim-to-hub backing','heater radialroute and metric camera calibration','whole-stage static/motion/service and radiator context']}
if __name__=='__main__':
 R=Path(__file__).resolve().parents[1]
 (R/'reference/engine/pump-metric-20261002-contract.json').write_text(json.dumps({'status':'Proposed next coordinated height candidate only; no CAD created','metric_value':pump_height_datums(),'inch_conversion_sensitivity':pump_height_datums(3.88*25.4),'difference_is_catalog_conversion_not_tolerance':True},indent=2)+'\n')
