"""Optional export binding only: rigidly transform root's qualified analytic mesh."""
from pathlib import Path
import sys,json,hashlib,numpy as np,trimesh
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R/'cad/engine'))
import build123d as b
import pump_cover_candidate_20261003 as c
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();src=R/'cad/engine/generated/pump-spring-sweep-20261003/spring-analytic.glb';pr=R/'reference/engine/pump-spring-sweep-20261003-analytic-check.json';prior=json.loads(pr.read_text());assert sha(src)==prior['glb_sha256'];assert prior['status'].startswith('PASS');g=trimesh.load(src,force='mesh');v=g.vertices[:,[0,2,1]]*[1,-1,1]*1000;tr=c.T.wrapped.Transformation();matrix=np.array([[tr.Value(i,j)for j in range(1,5)]for i in range(1,4)]);vv=np.c_[v,np.ones(len(v))]@matrix.T;gp=c.O/'water-pump-seal-spring.glb';trimesh.Trimesh(vv[:,[0,2,1]]*[1,1,-1]/1000,g.faces,process=False).export(gp);new=trimesh.load(gp,force='mesh');verts=new.vertices[:,[0,2,1]]*[1,-1,1]*1000;m=trimesh.Trimesh(verts,new.faces,process=False);sp=c.O/'water-pump-seal-spring.step';s=b.import_step(sp);shell=s.shells()[0];rng=np.random.default_rng(20261003);ids=rng.choice(len(m.faces),400,replace=False);caps=np.where(abs(m.face_normals[:,0])>.99999)[0];ids=np.unique(np.r_[ids,rng.choice(caps,min(100,len(caps)),replace=False)]);dist=[]
for i,p in enumerate(m.triangles_center[ids]):
 dist.append(float(b.Vertex(*p).distance_to(shell)))
 if i%100==0:print('sample',i,flush=True)
expected=np.array([[406.93,c.Y-15.9,c.Z-15.9],[411.43,c.Y+15.9,c.Z+15.9]]);err=float(abs(m.bounds-expected).max());r={'status':'PASS optional export finitecheck'if max(dist)<=.025 and err<=.025 and new.is_watertight and new.is_winding_consistent and len(new.split())==1 else'FAIL','path':str(gp.relative_to(R)),'sha256':sha(gp),'step_sha256':sha(sp),'watertight':new.is_watertight,'winding':new.is_winding_consistent,'components':len(new.split()),'faces':len(new.faces),'samples':len(dist),'surface_max_mm':max(dist),'surface_distances_mm':dist,'cad_bounds_error_mm':err,'bounds_gate_mm':.025,'bounds_provenance':'Root analytic original helix trim bounds, rigidly transformed; native STEP spline hull is loose','original_root_inputs':{str(p.relative_to(R)):sha(p)for p in [src,pr,R/'docs/components/pump-spring-sweep-20261003-handoff.md']},'inputs':{str(p.relative_to(R)):sha(p)for p in [Path(__file__),Path(c.__file__),sp]},'scope':'Optional GLB only; original STEP shape rigidly relocated. No geometry/mass/preload or production acceptance.'};(R/'reference/engine/pump-cover-candidate-20261003-spring-mesh.json').write_text(json.dumps(r,indent=2)+'\n');print({k:v for k,v in r.items()if k!='surface_distances_mm'})
