"""Illustrate why uncalibrated view-up is not a physical axial coordinate."""
from pathlib import Path
import json,hashlib,numpy as np
R=Path(__file__).resolve().parents[1];O=R/'cad/engine/generated/waterpump-heater-route-evidence';O.mkdir(exist_ok=True)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
src=R/'inventory/engine/waterpump-heater-source-registration.json';j=json.loads(src.read_text());f=np.array(j['source_fits']['front']['model_yz_NOT_MEASURED']);b=np.array(j['source_fits']['rear']['model_yz_NOT_MEASURED'])
views={'retailer_side':{'rear_y':307.,'hub_y':65.,'root_y':249.,'tip_y':543.,'image':'reference/engine/gates44009-3.jpg'},'manufacturer_catalog_oblique':{'rear_y':117.,'hub_y':37.,'root_y':94.,'tip_y':143.,'image':'PDF309 first embedded image307x170px; rear-center partly hidden estimate'}}
for v in views.values():
 scale=143/(v['rear_y']-v['hub_y']);v['root_X_under_invalid_1D_projection']=375+(v['rear_y']-v['root_y'])*scale;v['tip_X_under_invalid_1D_projection']=375+(v['rear_y']-v['tip_y'])*scale
paths=[Path(__file__),src,R/'docs/components/waterpump-heater-route-evidence.md',R/'inventory/engine/waterpump-heater-source-delivery.json',R/'inventory/engine/corrected-engine-stage-v3.json',R/'reference/engine/research-2026-09-23/gates-water-pumps-2011.pdf',*[R/'reference/engine'/('gates44009-'+str(i)+'.jpg')for i in [1,2,3]],*[R/'reference/photos/2026-09-23'/('engine-bay-'+s+'-side.jpg')for s in ['driver','passenger']]]
r={'status':'RESEARCH COMPLETE; physical3D route envelope UNKNOWN; no CAD repair authorized by this evidence','views':views,'front_rear_projected_root_disagreement_model_mm':float(np.linalg.norm(f[0]-b[0])),'front_rear_projected_tip_disagreement_model_mm':float(np.linalg.norm(f[-1]-b[-1])),'naive_tipX_estimator_spread_mm':[min(v['tip_X_under_invalid_1D_projection']for v in views.values()),max(v['tip_X_under_invalid_1D_projection']for v in views.values())],'physical_guaranteed_envelope':'UNKNOWN; observed-estimator interval is not a conservative physical bound','source_application':{'primary_url':'https://cms.gates.com/~/media/Files/Gates/Industrial/Fluid%20Power/Catalogs/Water%20Pump%20Catalog%20Full%20Version.pdf','application':'1993–1996 FordF-series4.9L →44009, PDF55','photo':'Printed289/PDF309 explicitly identifies44009 with long formed tube','dimensions':'None for tube route'},'owner_review':{'observed':'Paired red/orange hoses toward engine front; short exposed metal portions.','obscured':'Casting insertion and complete tube route; no secure hose-to-pump trace or metric axial datum.','not_claimed':'Neither frozen boundary validated; no identity from hose color.'},'controls':{'wrong_mirror_and_index':'Existing hash-bound registration report retains controls; no new axis flip.','independent_photo_same_naive_calibration':'Large axial endpoint disagreement rejects unique1D projection interpretation.','frozen_failures_retained':'Five actual tube-neighbor intersections remain; no CAD or stage writes.'},'inputs':{str(p.relative_to(R)):sha(p)for p in paths}}
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
fig,axs=plt.subplots(1,2,figsize=(12,5))
for name,v in views.items():axs[0].plot([v['tip_X_under_invalid_1D_projection'],v['root_X_under_invalid_1D_projection']],[name,name],'o-',label=name)
axs[0].axvline(375,color='gray',ls=':',label='retained rear375');axs[0].set(xlabel='Apparent X from naive image-up mapping (mm)',title='Same inadequate calibration, incompatible endpoints');axs[0].tick_params(axis='y',labelsize=8);axs[0].grid(alpha=.3)
for name,q in [('front',f),('rear',b)]:axs[1].plot(q[:,0],q[:,1],'o--',label=name+' registered projection')
axs[1].set(xlabel='Local Y in inherited model scale',ylabel='Local Z in inherited model scale',title='Root agrees; far endpoint does not');axs[1].axis('equal');axs[1].legend();axs[1].grid(alpha=.3);fig.suptitle('Photographic estimator spread — NOT a physical tolerance or bounded3D envelope');fig.tight_layout();p=O/'review.png';fig.savefig(p,dpi=160);r['diagram']={'path':str(p.relative_to(R)),'sha256':sha(p)};(R/'inventory/engine/waterpump-heater-route-evidence.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items()if k not in ['inputs','owner_review','controls']},indent=2))
